# Generated by Django 5.1.7 on 2025-03-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domains',
            options={'verbose_name': 'Домены', 'verbose_name_plural': 'Домен'},
        ),
        migrations.AddField(
            model_name='domains',
            name='description',
            field=models.CharField(default='', max_length=600, verbose_name='Meta-description главной страницы'),
        ),
        migrations.AddField(
            model_name='domains',
            name='favicon',
            field=models.ImageField(null=True, upload_to='favicons/', verbose_name='favicon .ico'),
        ),
        migrations.AddField(
            model_name='domains',
            name='keywords',
            field=models.CharField(default='', max_length=500, verbose_name='Meta-keywords главной страницы'),
        ),
        migrations.AddField(
            model_name='domains',
            name='title',
            field=models.CharField(default='', max_length=500, verbose_name='Title главной страницы'),
        ),
    ]
