# Generated by Django 5.1.7 on 2025-03-21 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0002_alter_domains_options_domains_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domains',
            name='favicon',
            field=models.ImageField(help_text='фавикон в формате .ico', null=True, upload_to='favicons/', verbose_name='favicon'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('description', models.CharField(max_length=500, verbose_name='Meta-description')),
                ('slug', models.SlugField(verbose_name='URL')),
                ('img_preview', models.ImageField(null=True, upload_to='img/', verbose_name='Превью')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('text', models.TextField(verbose_name='Текст статьи')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pbn.domains', verbose_name='Домен')),
            ],
            options={
                'verbose_name': 'Статьи',
                'verbose_name_plural': 'Статья',
            },
        ),
    ]
