# Generated by Django 5.1.7 on 2025-03-22 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0004_article_text_preview_alter_article_img_preview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статьи', 'verbose_name_plural': 'Статью'},
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(verbose_name='URL')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pbn.domains', verbose_name='Домен')),
            ],
            options={
                'verbose_name': 'Категории',
                'verbose_name_plural': 'Категорию',
                'ordering': ['-domain', '-name'],
            },
        ),
    ]
