# Generated by Django 5.1.7 on 2025-03-22 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0007_alter_article_text_preview'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(verbose_name='URL')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pbn.domains', verbose_name='Домен')),
            ],
            options={
                'verbose_name': 'Страницу',
                'verbose_name_plural': 'Другие страницы',
            },
        ),
    ]
