# Generated by Django 5.1.7 on 2025-03-22 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0008_otherpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slug',
            new_name='category_slug',
        ),
    ]
