# Generated by Django 5.1.7 on 2025-03-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0011_domains_h1_domains_logo_domains_main_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domains',
            options={'verbose_name': 'Домен', 'verbose_name_plural': 'Домены'},
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default='', max_length=600, verbose_name='Meta-description'),
        ),
        migrations.AddField(
            model_name='category',
            name='h1',
            field=models.CharField(default='', max_length=250, verbose_name='Заголовок H1'),
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(default='', max_length=250, verbose_name='Title'),
        ),
    ]
