# Generated by Django 5.1.7 on 2025-03-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0012_alter_domains_options_category_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherpage',
            name='description',
            field=models.CharField(default='', max_length=600, verbose_name='Meta-description'),
        ),
        migrations.AddField(
            model_name='otherpage',
            name='h1',
            field=models.CharField(default='', max_length=250, verbose_name='Заголовок H1'),
        ),
        migrations.AddField(
            model_name='otherpage',
            name='text',
            field=models.TextField(default='', verbose_name='Текст статьи'),
        ),
        migrations.AddField(
            model_name='otherpage',
            name='title',
            field=models.CharField(default='', max_length=250, verbose_name='Title'),
        ),
    ]
