# Generated by Django 5.1.7 on 2025-03-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0015_alter_domains_blog_keywords_alter_domains_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img_preview',
            field=models.ImageField(null=True, upload_to='static/pbn/img', verbose_name='Картинка-превью'),
        ),
        migrations.AlterField(
            model_name='domains',
            name='favicon',
            field=models.ImageField(help_text='фавикон в формате .ico', null=True, upload_to='static/pbn/favicons', verbose_name='favicon'),
        ),
    ]
