# Generated by Django 5.1.7 on 2025-03-28 07:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0016_alter_article_img_preview_alter_domains_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domains',
            name='main_text',
            field=ckeditor.fields.RichTextField(verbose_name='Текст на главной'),
        ),
    ]
