# Generated by Django 5.1.7 on 2025-03-28 07:48

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0017_alter_domains_main_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domains',
            name='main_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст на главной'),
        ),
    ]
