# Generated by Django 5.1.7 on 2025-03-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0019_alter_article_text_alter_otherpage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(help_text='При создании поставьте любой символ. Поле заполнится автоматически.', max_length=200, verbose_name='URL'),
        ),
    ]
