# Generated by Django 5.1.7 on 2025-03-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0021_alter_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_slug',
            field=models.SlugField(help_text='При создании поставьте любой символ. Поле заполнится автоматически.', max_length=100, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='otherpage',
            name='slug',
            field=models.SlugField(help_text='При создании поставьте любой символ. Поле заполнится автоматически.', max_length=100, verbose_name='URL'),
        ),
    ]
