# Generated by Django 5.1.7 on 2025-03-30 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0022_alter_category_category_slug_alter_otherpage_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 30, 9, 33, 58, 606411), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sort',
            field=models.IntegerField(default=100, help_text='Чем ближе к нулю,тем выше', verbose_name='Сортировка'),
        ),
        migrations.AlterField(
            model_name='otherpage',
            name='sort',
            field=models.IntegerField(default=100, help_text='Чем ближе к нулю,тем выше', verbose_name='Сортировка'),
        ),
    ]
