# Generated by Django 5.1.7 on 2025-03-30 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0023_alter_article_created_alter_category_sort_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2025, 3, 30, 9, 35, 48, 941609), verbose_name='Дата создания'),
        ),
    ]
