# Generated by Django 5.1.7 on 2025-03-30 07:09

import ckeditor_uploader.fields
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0025_alter_article_created_alter_domains_blog_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2025, 3, 30, 10, 9, 25, 782187), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img_preview',
            field=models.ImageField(null=True, upload_to='static/pbn/img', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg'))], verbose_name='Картинка-превью'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Не менее 300 символов', validators=[django.core.validators.MinLengthValidator(300)], verbose_name='Содержание статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text_preview',
            field=models.TextField(default='', max_length=300, verbose_name='Текст-превью'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(default='', max_length=500, verbose_name='Meta-description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='domains',
            name='favicon',
            field=models.ImageField(help_text='фавикон в формате .ico', null=True, upload_to='static/pbn/favicons', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('ico',))], verbose_name='favicon'),
        ),
        migrations.AlterField(
            model_name='domains',
            name='logo',
            field=models.ImageField(help_text='Форматы:png, jpg, jpeg', null=True, upload_to='static/pbn/img', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg'))], verbose_name='Логотип сайта'),
        ),
        migrations.AlterField(
            model_name='domains',
            name='main_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Не менее 300 символов', validators=[django.core.validators.MinLengthValidator(300)], verbose_name='Текст на главной'),
        ),
        migrations.AlterField(
            model_name='otherpage',
            name='description',
            field=models.CharField(default='', max_length=500, verbose_name='Meta-description'),
        ),
        migrations.AlterField(
            model_name='otherpage',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='otherpage',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Содержание'),
        ),
    ]
