# Generated by Django 5.1.7 on 2025-04-02 07:17

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0026_alter_article_created_alter_article_img_preview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2025, 4, 2, 10, 17, 12, 94347), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text_preview',
            field=models.TextField(default='', help_text='Не более 300 символов вместе с пробелами', max_length=300, verbose_name='Текст-превью'),
        ),
        migrations.AlterField(
            model_name='domains',
            name='logo',
            field=models.ImageField(help_text='Форматы: png, jpg, jpeg', null=True, upload_to='static/pbn/img', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg'))], verbose_name='Логотип сайта'),
        ),
        migrations.CreateModel(
            name='MembransLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_user', models.SlugField(help_text='Символный код ссылки-прокладки. Только латиница в нижним регистре и тире. Например: my-new-link', max_length=100, verbose_name='URL-прокладки')),
                ('link_money_site', models.CharField(help_text='URL финальной страницы на Money Site', max_length=150, verbose_name='URL Money Site')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pbn.domains', verbose_name='Домен')),
            ],
            options={
                'verbose_name': 'Прокладку',
                'verbose_name_plural': 'Ссылки-прокладки',
            },
        ),
    ]
